version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: esports_db
      MYSQL_USER: esports_user
      MYSQL_PASSWORD: esports_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - esports_network
    command: --default-authentication-plugin=mysql_native_password

  importer:
    build: ./importer
    container_name: importer
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: esports_db
      DATABASE_USER: esports_user
      DATABASE_PASSWORD: esports_password
      S3_BUCKET_NAME: vcthackathon-data
      S3_BUCKET_PREFIX: vct-international/
    networks:
      - esports_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - esports_network

networks:
  esports_network:

volumes:
  mysql_data:

